[phases.setup]
nixPkgs = [
  "nodejs_20",
  "stdenv.cc.cc.lib",
  "python3",
  "gnumake",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = ["npm ci --build-from-source"]

[phases.build]

[start]
cmd = "node server.js"
